name: Create Release on Merge
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.pull_request.head.ref }}
          release_name: ${{ github.event.pull_request.head.ref }}
          body: |
            Pull Request Title: ${{ github.event.pull_request.title }}
            Pull Request Description: ${{ github.event.pull_request.body }}
          draft: false
          prerelease: false

