name: Create Release on Merge
on:
  pull_request:
    types: [closed]
    branches:
      - 'main'     
  workflow_dispatch:
    inputs:
      new-release:
        description: 'The name of the new release'
        required: true

env:
  NEW_BRANCH_NAME: release-2.0.0

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ github.event.pull_request.head.ref }}
          tag_name: ${{ github.event.pull_request.head.ref }}
          body: |
            ${{ github.event.pull_request.body }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
      - name: Create Branch
        run: |
          git checkout -b ${{ inputs.new-release }}
          git push origin ${{ inputs.new-release }}